### ISSUE TITLE
perl/tcsh/vim fail on launch in RedHat/Fedora/CentOS w/ libfreebl3.so,and prelink

### ISSUE THREAD

**Issue by gc00** [dmtcp/dmtcp#104]
There is a race condition on DMTCP launch.  So, sometimes DMTCP restart crashes with a segfault.
Here is a typical case where it happens:

    yum install prelink
    ulimit -c unlimited
    cd dmtcp
    make -j check-perl
    # Or alternatively:
    cd dmtcp
    make tidy
    bin/dmtcp_launch -i5 /usr/bin/perl
    bin/dmtcp_restart ckpt_perl_*.dmtcp
    [ segfault ]

I know a lot about the bug.  At batlab.org (on Red Hat 6), the race condition reliably triggers the bug.  It shows that perl calls libfreebl3.so,nwhich calls vfork, and the child execs into prelink.  Soon after this,
a SIGCHLD is sent to perl (presumably due to prelink exiting), and perl enters a SIGCHLD handler.  But I have no idea which handler this is.  libfreebl3.so has one SIGCHLD handler, but I'm pretty sure that what I'm seeing is a different one.  The new handler segfaults on returning with the instruction pointer set to 0.

Unfortunately, there does not exists a debuginfo package for libfreebl3.so under CentOS.  So, I can't get debug symbols in GDB.

Unfortunately, while I can build libfreebl3.so from source on some local
CentOS6 VMs with libfreebl3.so and prelink, I can't triffer the bug.   I can't build libfreebl3 on CentOS7.  And even if I could build it on CentOS7, on CentOS7, gdb is complaining of a truncated core file.  So, I don't even know if the debuginfo would help.

Based on Google, libfreebl3.so seems related to FIPS security.

Here is a typical stack trace:

    (gdb) where
    #0  0x0000000000000000 in ?? ()
    #1  0x0000003bdb22b68d in ?? () from /lib64/libfreebl3.so
    #2  <signal handler called>
    #3  0x00002aaaaaf62bfc in std::map<int, int, std::less<int>, dmtcp::DmtcpAlloc<std::pair<int, int> >     >::end (this=0x2aaaab8b5340)
        at /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_map.h:325
    #4  0x00002aaaaaf61ad2 in dmtcp::VirtualIdTable<int>::realIdExists (
        this=0x2aaaab8b5308, id=0) at ../../../include/virtualidtable.h:151
    #5  0x00002aaaab6a8eaa in dmtcp::VirtualPidTable::realToVirtual (
        this=0x2aaaab8b5308, realPid=0) at virtualpidtable.cpp:122
    #6  0x00002aaaab6a8184 in wait4 (pid=41000, status=0x7fffffffca84, options=0, 
        rusage=0x0) at pidwrappers.cpp:487
    #7  0x00002aaaab458db4 in _real_wait4 ()
       from /slots/04/dir_60629/dmtcp/lib/dmtcp/libdmtcp.so
    #8  0x00002aaaab41d8e3 in wait4 (pid=41000, status=0x7fffffffca84, options=0, 
        rusage=0x0) at miscwrappers.cpp:195
    #9  0x00002aaaab41d860 in waitpid (pid=41000, stat_loc=0x0, options=0)
        at miscwrappers.cpp:176
    #10 0x0000003bdb22b60b in ?? () from /lib64/libfreebl3.so
    ...
    #18 0x0000003bdb203a7b in ?? () from /lib64/libfreebl3.so
    #19 0x00002aaaab8c7178 in ?? ()
    #20 0x0000003bd460e605 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
    #21 0x0000003bd4600b3a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2

**Comment by gc00** [comment]
I have placed a notice about this problem on the release announcement for 2.4.0 at http://dmtcp.sourceforge.net/index.html , and I will probably add something similar to the NEWS file before the release.  Without a debuginfo package or a build with -g, it's difficult to understand what libfreebl3.so is doing.
