### ISSUE TITLE
Bug in pthread2 (seen on RISC-V, glibc-2.37): detached threads

### ISSUE THREAD

**Issue by gc00** [dmtcp/dmtcp#1163]
On restart, usually on thread 4, we see:

> (gdb) where
#0  0x0000003ff7bd2c2e in list_del (elem=0x3fef8bc220) at ../include/list.h:55
#1  __GI___nptl_stack_list_del (elem=0x3fef8bc220) at nptl-stack.c:32
#2  __GI___nptl_deallocate_stack (pd=pd@entry=0x3fef8bc160) at nptl-stack.c:116
#3  0x0000003ff7bd2e1a in __GI___nptl_free_tcb (pd=0x3fef8bc160) at nptl_free_tcb.c:42
#4  0x0000003ff7bd5422 in start_thread (arg=<optimized out>) at pthread_create.c:575
#5  0x0000003ff7c2bfca in __thread_start () at ../sysdeps/unix/sysv/linux/riscv/clone.S:85  

glibc wants to free the stack and tcb of a detached head, before starting the new thread start function (threadMain).
In doing this, the pd (type: struct pthread) has a list field (type: list_t)..

Most of the 'pd' for threads have addresses like ` (struct pthread *) 0x3fef8bc160`..  But for thread 4:
> (gdb) p pd->list
$7 = {next = 0x3f00009c6c, prev = 0x3fef9bd220} 

and `0x3f00009c6c` is not mapped.

Most other threads have a stack:
> (gdb) where
#0  futex_wait (private=0, expected=2, futex_word=0x140d0 <dl_main+8766>) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x140d0 <dl_main+8766>, private=0) at lowlevellock.c:49
#2  0x0000003ff7bd7fe6 in lll_mutex_lock_optimized (mutex=0x140d0 <dl_main+8766>) at pthread_mutex_lock.c:48
#3  ___pthread_mutex_lock (mutex=0x140d0 <dl_main+8766>) at pthread_mutex_lock.c:93
#4  0x000000000001135a in process_dl_debug (state=<optimized out>, dl_debug=<optimized out>) at rtld.c:2537
Backtrace stopped: frame did not save the PC 

Thread 1 is still in rtld:
> (gdb) where
#0  0x0000003ff7c01094 in __GI___clock_nanosleep (clock_id=<optimized out>, clock_id@entry=0, flags=flags@entry=0,          
    req=req@entry=0x3fffffe748, rem=rem@entry=0x3fffffe748) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
#1  0x0000003ff7c051c0 in __GI___nanosleep (req=req@entry=0x3fffffe748, rem=rem@entry=0x3fffffe748)
    at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x0000003ff7c050ea in __sleep (seconds=0) at ../sysdeps/posix/sleep.c:55
#3  0x0000000000011276 in do_preload (
    fname=0xfffffffffffffdfc <error: Cannot access memory at address 0xfffffffffffffdfc>, main_map=0x0,
    where=0x1 <error: Cannot access memory at address 0x1>) at rtld.c:819
#4  0x0000003ff7b8c3c8 in __libc_start_call_main (main=main@entry=0x111b4 <print_unresolved>, argc=1, argc@entry=999,       
    argv=argv@entry=0x3fffffe9b8) at ../sysdeps/nptl/libc_start_call_main.h:58
#5  0x0000003ff7b8c474 in __libc_start_main_impl (main=0x111b4 <print_unresolved>, argc=999, argv=0x3fffffe9b8,
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=<optimized out>)
    at libc-start.c:360
#6  0x0000000000011140 in lookup_doit (a=0x3fffffe9b0) at rtld.c:671
    Backtrace stopped: previous frame inner to this frame (corrupt stack?)  

Thread 7 is the checkpoint thread:
> (gdb) where
#0  0x0000003ff7c212b8 in __GI___libc_read (nbytes=208, buf=0x3ff05bf718, fd=<optimized out>)
    at ../sysdeps/unix/sysv/linux/read.c:26
#1  __GI___libc_read (fd=<optimized out>, buf=0x3ff05bf718, nbytes=208) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x0000003ff7db0dec in dmtcp::Util::readAll (fd=821, buf=0x3ff05bf718, count=208) at util_misc.cpp:191
#3  0x0000003ff7d94aae in dmtcp::CoordinatorAPI::recvMsgFromCoordinatorRaw (fd=821, msg=0x3ff05bfb78, extraData=0x0)
    at coordinatorapi.cpp:380
#4  0x0000003ff7d94d22 in dmtcp::CoordinatorAPI::recvMsgFromCoordinator (msg=0x3ff05bfb78, extraData=0x0)
    at coordinatorapi.cpp:426
#5  0x0000003ff7d7704e in dmtcp::DmtcpWorker::waitForPreSuspendMessage () at dmtcpworker.cpp:333
#6  0x0000003ff7d773da in dmtcp::DmtcpWorker::waitForCheckpointRequest () at dmtcpworker.cpp:363
#7  0x0000003ff7d8a6a4 in checkpointhread (dummy=0x0) at threadlist.cpp:427
#8  0x0000003ff7d8dc8c in thread_start (arg=0x3ff680f008) at threadwrappers.cpp:77
#9  0x0000003ff7bd531c in start_thread (arg=<optimized out>) at pthread_create.c:444
#10 0x0000003ff7c2bfca in __thread_start () at ../sysdeps/unix/sysv/linux/riscv/clone.S:85 

~~~~

When stopping early at DMTCP_RESTART_PAUSE=5:

Thread 4:
> (gdb) p/x ((struct pthread *)pthread_self())->list
$13 = {next = 0x3f00009c6c, prev = 0x3fef9bd220} 

And this is always in Thread 4:

Thread 4:
> NOTE libc message:  "The futex facility returned an unexpected error code.\n")
(gdb) where
#0  0x0000003ff7bd6cbe in __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6,
    no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x0000003ff7bd6d12 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x0000003ff7b9d9c8 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x0000003ff7b8c1f6 in __GI_abort () at abort.c:79
#4  0x0000003ff7bcd3ae in __libc_message (fmt=fmt@entry=0x3ff7c8c790 "%s") at ../sysdeps/posix/libc_fatal.c:150
#5  0x0000003ff7bcd3d0 in __GI___libc_fatal (
    message=message@entry=0x3ff7c87388 "The futex facility returned an unexpected error code.\n")
    at ../sysdeps/posix/libc_fatal.c:159
#6  0x0000003ff7bd2870 in futex_fatal_error () at ../sysdeps/nptl/futex-internal.h:87
#7  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x3ff7e01880 <semWaitForCkptThreadSignal>,
    expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>,
    cancel=cancel@entry=true) at futex-internal.c:119
#8  0x0000003ff7bd28d4 in __GI___futex_abstimed_wait_cancelable64 (
    futex_word=futex_word@entry=0x3ff7e01880 <semWaitForCkptThreadSignal>, expected=expected@entry=0,
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>) at futex-internal.c:139
#9  0x0000003ff7bdc3d6 in do_futex_wait (sem=sem@entry=0x3ff7e01880 <semWaitForCkptThreadSignal>, abstime=0x0,
    clockid=0) at /usr/src/debug/glibc-2.37-5.fc38.riscv64/nptl/sem_waitcommon.c:111
#10 0x0000003ff7bdc470 in __new_sem_wait_slow64 (sem=0x3ff7e01880 <semWaitForCkptThreadSignal>, abstime=0x0, clockid=0)
    at /usr/src/debug/glibc-2.37-5.fc38.riscv64/nptl/sem_waitcommon.c:183
#11 0x0000003ff7d8ba2c in dmtcp::ThreadList::waitForAllRestored (thread=0x3ff680e008) at threadlist.cpp:720
#12 0x0000003ff7d8b81c in stopthisthread (signum=12) at threadlist.cpp:666
#13 <signal handler called>
#14 futex_wait (private=0, expected=2, futex_word=0x140d0 <mutex>) at ../sysdeps/nptl/futex-internal.h:146
#15 __GI___lll_lock_wait (futex=futex@entry=0x140d0 <mutex>, private=0) at lowlevellock.c:49
#16 0x0000003ff7bd7fe6 in lll_mutex_lock_optimized (mutex=0x140d0 <mutex>) at pthread_mutex_lock.c:48
#17 ___pthread_mutex_lock (mutex=0x140d0 <mutex>) at pthread_mutex_lock.c:93
#18 0x000000000001135a in threadMain (data=0x27d20) at pthread2.c:69
#19 0x0000003ff7d8dc8c in thread_start (arg=0x3ff680e008) at threadwrappers.cpp:77
--Type <RET> for more, q to quit, c to continue without paging--
#20 0x0000003ff7bd531c in start_thread (arg=<optimized out>) at pthread_create.c:444
#21 0x0000003ff7c2bfca in __thread_start () at ../sysdeps/unix/sysv/linux/riscv/clone.S:85

Thread 5:
> (gdb) thread 5
[Switching to thread 5 (LWP 1388945)]
#0  0x0000003ff7bd289e in __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0,
op=<optimized out>, expected=0, futex_word=0x3ff7e01880 <semWaitForCkptThreadSignal>) at futex-internal.c:57
57          return INTERNAL_SYSCALL_CANCEL (futex_time64, futex_word, op, expected,
(gdb) where
#0  0x0000003ff7bd289e in __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0,
    op=<optimized out>, expected=0, futex_word=0x3ff7e01880 <semWaitForCkptThreadSignal>) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x3ff7e01880 <semWaitForCkptThreadSignal>,
    expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>,
    cancel=cancel@entry=true) at futex-internal.c:87
#2  0x0000003ff7bd28d4 in __GI___futex_abstimed_wait_cancelable64 (
    futex_word=futex_word@entry=0x3ff7e01880 <semWaitForCkptThreadSignal>, expected=expected@entry=0,
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>) at futex-internal.c:139
#3  0x0000003ff7bdc3d6 in do_futex_wait (sem=sem@entry=0x3ff7e01880 <semWaitForCkptThreadSignal>, abstime=0x0,
clockid=0) at /usr/src/debug/glibc-2.37-5.fc38.riscv64/nptl/sem_waitcommon.c:111
#4  0x0000003ff7bdc470 in __new_sem_wait_slow64 (sem=0x3ff7e01880 <semWaitForCkptThreadSignal>, abstime=0x0, clockid=0)     at /usr/src/debug/glibc-2.37-5.fc38.riscv64/nptl/sem_waitcommon.c:183
#5  0x0000003ff7d8ba2c in dmtcp::ThreadList::waitForAllRestored (thread=0x3ff680e408) at threadlist.cpp:720
#6  0x0000003ff7d8b81c in stopthisthread (signum=12) at threadlist.cpp:666
#7  <signal handler called>
#8  futex_wait (private=0, expected=2, futex_word=0x140d0 <mutex>) at ../sysdeps/nptl/futex-internal.h:146
#9  __GI___lll_lock_wait (futex=futex@entry=0x140d0 <mutex>, private=0) at lowlevellock.c:49
#10 0x0000003ff7bd7fe6 in lll_mutex_lock_optimized (mutex=0x140d0 <mutex>) at pthread_mutex_lock.c:48
#11 ___pthread_mutex_lock (mutex=0x140d0 <mutex>) at pthread_mutex_lock.c:93
#12 0x000000000001135a in threadMain (data=0x27eb0) at pthread2.c:69
#13 0x0000003ff7d8dc8c in thread_start (arg=0x3ff680e408) at threadwrappers.cpp:77
#14 0x0000003ff7bd531c in start_thread (arg=<optimized out>) at pthread_create.c:444
#15 0x0000003ff7c2bfca in __thread_start () at ../sysdeps/unix/sysv/linux/riscv/clone.S:85  

And Thread 7 (ckpt thread):
> (gdb) where
#0  0x0000003ff7bd289e in __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0,
    op=<optimized out>, expected=0, futex_word=0x3ff7e01860 <semNotifyCkptThread>) at futex-internal.c:57
#1  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x3ff7e01860 <semNotifyCkptThread>,
    expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>,
    cancel=cancel@entry=true) at futex-internal.c:87
#2  0x0000003ff7bd28d4 in __GI___futex_abstimed_wait_cancelable64 (
    futex_word=futex_word@entry=0x3ff7e01860 <semNotifyCkptThread>, expected=expected@entry=0,
    clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>) at futex-internal.c:139
#3  0x0000003ff7bdc3d6 in do_futex_wait (sem=sem@entry=0x3ff7e01860 <semNotifyCkptThread>, abstime=0x0, clockid=0)
    at /usr/src/debug/glibc-2.37-5.fc38.riscv64/nptl/sem_waitcommon.c:111
#4  0x0000003ff7bdc470 in __new_sem_wait_slow64 (sem=0x3ff7e01860 <semNotifyCkptThread>, abstime=0x0, clockid=0)
    at /usr/src/debug/glibc-2.37-5.fc38.riscv64/nptl/sem_waitcommon.c:183
#5  0x0000003ff7d8b956 in dmtcp::ThreadList::waitForAllRestored (thread=0x3ff680f008) at threadlist.cpp:686
#6  0x0000003ff7d8a6a0 in checkpointhread (dummy=0x0) at threadlist.cpp:416
#7  0x0000003ff7d8dc8c in thread_start (arg=0x3ff680f008) at threadwrappers.cpp:77
#8  0x0000003ff7bd531c in start_thread (arg=<optimized out>) at pthread_create.c:444
#9  0x0000003ff7c2bfca in __thread_start () at ../sysdeps/unix/sysv/linux/riscv/clone.S:85

**Comment by gc00** [comment]
This bug is fixed by PR #1165.  We are still resolving what is the cleanest version of the code to push in for that commit.  When PR #1165 will be pushed in, this bug will be ffixed.
