### ISSUE TITLE
User thread should wait until ckpt thread calls select on coord socket

### ISSUE THREAD

**Issue by gc00** [dmtcp/dmtcp#247]
One of the principles of DMTCP is that either the checkpoint thread or the user threads can run, but normally not both at the same time.

This principle seems to be violated in the startup of the checkpoint thread during launch.  It leads to a real bug.  To illustrate, try:
```
bin/dmtcp_launch --no-coordinator tcsh
```
There is a race condition under which it will usually succeed, but sometimes fail with a SEGFAULT in the `malloc()` routine of tcsh.  (tcsh defines its own `malloc()`.)  I then observed tcsh to segfault here:
```
0x000000000044a4ab in malloc (nbytes=24) at tc.alloc.c:222
222	    nextf[bucket] = nextf[bucket]->ov_next;
```

The reason is that the malloc() of tcsh calls sbrk() and the malloc() of glibc (used by DMTCP) calls sbrk().  In both instances of malloc(), they follow the pattern:  `begin_buf = sbrk(0); ... end_buf = sbrk(size);`

There is an obvious race that heppens when both instances ask for `morecore()` at the same time.  In the case of tcsh, DMTCP calls select(), which calls dlsym() (since select() is a wrapper), and dlsym() calls malloc().

A final proof that we have a race condition is that in `src/threadlist.cpp`, one can modify the code to pause the user thread until the checkpoint thread reaches select:
```
  JASSERT(pthread_create(&checkpointhreadid, NULL, checkpointhread, NULL) == 0);
  sleep(2);
```

After that, the race condition goes away.

The solution is to set up a semaphore. initialized to 0.  After calling pthread_create to create the ckpt thread, we should call `sem_wait()`.  The ckpt thread can then call `select()` trivially (which invokes dlsym the first time, and only the first time), and then the ckpt thread can call `sem_post()`, followed by its call to `select()` to wait on the coordinator.  [We use a similar semaphore solution on restart so that the checkpoint thread and user thread don't interact.]

Are there comments on this solution?  One possible downside is that startup of the user thread will be slightly delayed, but not by much.

**Comment by gc00** [comment]
Here is a little further explanation.  The checkpoint thread enters select() on the coordinator socket and then has this stack:
```
(gdb) where
#0  0x00007fbaf18fa3d3 in select () from /lib64/libc.so.6
#1  0x00007fbaf29f1228 in select (nfds=822, readfds=0x7fbaefa80d70, writefds=0x0, exceptfds=0x0, timeout=0x0)
    at ipc/event/eventwrappers.cpp:138
#2  0x00007fbaf2291a3f in dmtcp::CoordinatorAPI::waitForCheckpointCommand (this=0x7fbaf32732c8)
    at coordinatorapi.cpp:203
#3  0x00007fbaf228b511 in dmtcp::DmtcpWorker::waitForCoordinatorMsg (msgStr="SUSPEND", type=dmtcp::DMT_DO_SUSPEND)
    at dmtcpworker.cpp:385
#4  0x00007fbaf228bc37 in dmtcp::DmtcpWorker::waitForStage1Suspend () at dmtcpworker.cpp:461
#5  0x00007fbaf229e821 in dmtcp::callbackSleepBetweenCheckpoint (sec=0) at mtcpinterface.cpp:61
#6  0x00007fbaf22a9301 in checkpointhread (dummy=0x0) at threadlist.cpp:357
#7  0x00007fbaf22a0720 in pthread_start (arg=0x7fbaf3273288) at threadwrappers.cpp:159
#8  0x00007fbaf13e9555 in start_thread () from /lib64/libpthread.so.0
#9  0x00007fbaf22a03bb in clone_start (arg=0x7fbaf325f808) at threadwrappers.cpp:68
#10 0x00007fbaf203b4e2 in clone_start (arg=0x7fbaf32732c8) at pid/pid_miscwrappers.cpp:110
#11 0x00007fbaf1903f3d in clone () from /lib64/libc.so.6
```

But in Frame 6, the function checkpointhread() had already called `sem_post(&sem_start)`.  That call is too early.  DMTCP is still using glibc, and in particular, it will call `glibc:malloc()` through dlsym the first time it enters select().  So, `sem_post(&sem_start)` must be moved into frame 2, where there should be a trivial call to `select()` to trigger the dlsym/malloc, followed by `sem_post()`, followed by the actual call to `select()`.

**Comment by gc00** [comment]
PR #250 seems to fix this bug.  (Without some kind of formal verification, it's difficult to be sure with a manual check that a race condition is now impossible.)
