### ISSUE TITLE
SciPy in Python 3.5 hangs

### ISSUE THREAD

**Issue by PhaethonPrime** [dmtcp/dmtcp#426]
When using dmtcp with python, I am finding that a particular scipy module import causes the launch to hang. 

Here's the smallest example that illustrates it:
```
from __future__ import print_function
import scipy
from scipy import special
import dmtcp

def run():
    print("running")

if __name__ == "__main__":
    run()
```

After shutting down the process, this is the error:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from scipy import special
  File "/opt/miniconda/envs/vag-env/lib/python3.5/site-packages/scipy/special/__init__.py", line 627, in <module>
    from ._ufuncs import *
  File "scipy/special/_ufuncs.pyx", line 1, in init scipy.special._ufuncs (scipy/special/_ufuncs.c:26133)
  File "<frozen importlib._bootstrap>", line 966, in _find_and_load
KeyboardInterrupt
```

Has anyone run into this issue before? What can I do to help debug it?

Thanks in advance.

**Comment by rohgarg** [comment]
Thanks for reporting this, @PhaethonPrime. I can reproduce this locally. It seems like this only affects python3+ and not python2.x.

**Comment by solstag** [comment]
I'm also facing this, with python3.6
