### ISSUE TITLE
make check fails for pthread2 and pthread3 with newer libc (2.21)

### ISSUE THREAD

**Issue by karya0** [dmtcp/dmtcp#45]
The failure happens after the process has been successfully restarted.  It eventually segfaults right after resuming from a restart. Here is the backtrace for the segfaulting thread:

```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007f37ba7a1112 in unwind_stop (version=<optimized out>, actions=<optimized out>, 
    exc_class=<optimized out>, exc_obj=<optimized out>, context=<optimized out>, 
    stop_parameter=<optimized out>) at unwind.c:82
#2  0x00007f37b9966512 in ?? () from /lib64/libgcc_s.so.1
#3  0x00007f37b9966894 in _Unwind_ForcedUnwind () from /lib64/libgcc_s.so.1
#4  0x00007f37ba7a1180 in __GI___pthread_unwind (buf=<optimized out>) at unwind.c:126
#5  0x00007f37ba79b565 in __do_cancel () at pthreadP.h:283
#6  __pthread_exit (value=<optimized out>) at pthread_exit.c:28
#7  0x00007f37bac26ffe in _real_pthread_exit (retval=0x0) at syscallsreal.c:967
#8  0x00007f37babf43f3 in pthread_exit (retval=0x0) at threadwrappers.cpp:235
#9  0x0000000000400cee in threadMain (data=0x1b43d40) at pthread2.c:69
#10 0x00007f37babf40cc in pthread_start (arg=<optimized out>) at threadwrappers.cpp:159
#11 0x00007f37ba79a4b4 in start_thread (arg=0x7f37b7e12700) at pthread_create.c:333
#12 0x00007f37babf3f29 in clone_start (arg=0x7f37bb8de808) at threadwrappers.cpp:68
#13 0x00007f37ba4d8a4d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```

**Comment by gc00** [comment]
Nice catch!  Do we have a machine where I can observe this bug?
Thanks
- Gene

**Comment by karya0** [comment]
@rohgarg @jiajuncao @gc00: Any takers for this one? I observed this one on my laptop which is running OpenSUSE Tumbleweed with libc2.21 and Linux 3.19.1.

**Comment by gc00** [comment]
See issue #121, which could be related to this bug.   Issue #121 is reproducible even using the old libc-2.15 (Ubuntu&nbsp;12.04).
