### ISSUE TITLE
dmtcp_launch --no-coordinator crashes

### ISSUE THREAD

**Issue by heroxbd** [dmtcp/dmtcp#587]
$ dmtcp_launch --no-coordinator ls
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
[1]    28654 abort (core dumped)  dmtcp_launch --no-coordinator ls

The core-dump looks like:

```
gdb `which dmtcp_launch` core-dmtcp_launch.27964
(gdb) bt
#0  0x00007fd6740331c8 in raise () from /fefs/disk/usr100/gentoo/lib64/libc.so.6
#1  0x00007fd67403464a in abort () from /fefs/disk/usr100/gentoo/lib64/libc.so.6
#2  0x00007fd67496b22d in __gnu_cxx::__verbose_terminate_handler() () from /disk/usr100/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6
#3  0x00007fd674969066 in ?? () from /disk/usr100/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6
#4  0x00007fd6749690b1 in std::terminate() () from /disk/usr100/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6
#5  0x00007fd6749692c8 in __cxa_throw () from /disk/usr100/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6
#6  0x00007fd6749928df in std::__throw_logic_error(char const*) () from /disk/usr100/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6
#7  0x0000000000407de4 in std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> >::_M_construct<char*> (this=0x7fffb3283a20, __beg=0x0, __end=<optimized out>)
    at /disk/usr100/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/basic_string.tcc:216
#8  0x00000000004099bd in std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> >::_M_construct_aux<char const*> (
    __end=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>, __beg=0x0, this=0x7fffb3283a20)
    at /disk/usr100/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/basic_string.h:195
#9  std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> >::_M_construct<char const*> (__end=0xffffffffffffffff <error: Cannot access memory at address 0xffffffffffffffff>, 
    __beg=0x0, this=0x7fffb3283a20) at /disk/usr100/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/basic_string.h:214
#10 std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> >::basic_string (__a=..., __s=0x0, this=0x7fffb3283a20)
    at /disk/usr100/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/include/g++-v5/bits/basic_string.h:456
#11 dmtcp::CoordinatorAPI::setupVirtualCoordinator (this=this@entry=0x7fd6754ef008, coordInfo=coordInfo@entry=0x7fffb32843b0, localIP=localIP@entry=0x7fffb3283fb0) at coordinatorapi.cpp:168
#12 0x000000000040db64 in dmtcp::CoordinatorAPI::connectToCoordOnStartup (this=0x7fd6754ef008, mode=mode@entry=dmtcp::COORD_NONE, progname=..., compId=compId@entry=0x7fffb3283fd0, 
    coordInfo=coordInfo@entry=0x7fffb32843b0, localIP=localIP@entry=0x7fffb3283fb0) at coordinatorapi.cpp:577
#13 0x0000000000405596 in main (argc=<optimized out>, argv=0x7fffb3285408) at dmtcp_launch.cpp:548
```
What would you suggest for debugging this issue?

**Comment by rohgarg** [comment]
@heroxbd: I can't reproduce this issue locally with the master branch. It works on my system without any issues. Could you provide more details about your environment? Specifically, what DMTCP version and Linux distro are you using?

**Comment by heroxbd** [comment]
It is dmctp-2.5.0 from https://github.com/dmtcp/dmtcp/releases/tag/2.5.0.

The system is Gentoo Prefix installed on top of CentOS 6.5 (a shared cluster).  It has its own glibc in a directory prefix.

I have also tested with ordinary Gentoo, the same bug happened.

**Comment by rohgarg** [comment]
@heroxbd: This bug was introduced in commit: df0fe3f (before the 2.5.0 release) and was fixed later in commit: 69339f7d (after the 2.5.0 release). The fix should be a part of the next release (2.5.1).

**Comment by heroxbd** [comment]
@rohgarg Thank you for point this out.

master of 2.5 branch works perfectly.

I have backported  69339f7 to 2.5.0.  But it only works for standalone Gentoo.  On Gentoo Prefix, it fails on fortify related fault.

```
gdb ls core-ls.29270
Reading symbols from ls...(no debugging symbols found)...done.
[New LWP 29273]
[New LWP 29270]

warning: .dynamic section for "/fefs/disk/usr100/gentoo/usr/lib64/dmtcp/libdmtcp.so" is not at the expected address (wrong library or version mismatch?)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/fefs/disk/usr100/gentoo/lib64/libthread_db.so.1".
Core was generated by `ls'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f7c334801c8 in raise () from /fefs/disk/usr100/gentoo/lib64/libc.so.6
[Current thread is 1 (Thread 0x7f7c318bc700 (LWP 29273))]
(gdb) bt
#0  0x00007f7c334801c8 in raise () from /fefs/disk/usr100/gentoo/lib64/libc.so.6
#1  0x00007f7c3348164a in abort () from /fefs/disk/usr100/gentoo/lib64/libc.so.6
#2  0x00007f7c334bcc50 in ?? () from /fefs/disk/usr100/gentoo/lib64/libc.so.6
#3  0x00007f7c33545727 in __fortify_fail () from /fefs/disk/usr100/gentoo/lib64/libc.so.6
#4  0x00007f7c33543820 in __chk_fail () from /fefs/disk/usr100/gentoo/lib64/libc.so.6
#5  0x00007f7c33545697 in __fdelt_warn () from /fefs/disk/usr100/gentoo/lib64/libc.so.6
#6  0x00007f7c33a23d72 in dmtcp::CoordinatorAPI::resetOnFork (coordAPI=...) at coordinatorapi.cpp:146
#7  0x00007f7c322d5c01 in ?? ()
#8  0x00007f7c322d5c01 in ?? ()
#9  0x00007f7c322d5c00 in ?? ()
#10 0x00007f7c322d5c04 in ?? ()
#11 0x00007f7c322d5e00 in ?? ()
#12 0x00007f7c3344c240 in ?? () from /disk/usr100/gentoo/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6
#13 0x0000000000000010 in ?? ()
#14 0x00007f7c322d5c00 in ?? ()
#15 0x0000000000000001 in ?? ()
#16 0x0000000000000200 in ?? ()
#17 0x0000000000000000 in ?? ()
```

Just for your information.  I will use the master of 2.5 branch.
