### ISSUE TITLE
Failing on --enable-m32 in CentOS 7 and CentOS 6.6

### ISSUE THREAD

**Issue by gc00** [dmtcp/dmtcp#61]
These are probably two different bugs, but I'll start them as a single issue for now.
In CentOS 7, do:  `./configure --enable-m32` and make and `dmtcp_launch test/dmtcp1`.
`dmtcp_launch` correctly execs into `dtmcp1`.  Within DmtcpWorker, I see:
(gdb) where
#0  0xffffce30 in ?? ()
#1  0xf7e9e19e in initialize_libc_wrappers () at syscallsreal.c:265
#2  0xf7e50bfa in dmtcp_prepare_wrappers () at dmtcpworker.cpp:145
#3  0xf7ea0719 in _real_dup2 (oldfd=827, newfd=827) at syscallsreal.c:649
#4  0xf7e90a31 in jalib::dup2 (oldfd=827, newfd=827) at ../jalib/jalib.cpp:97
#5  0xf7e91669 in jassert_internal::jassert_init () at ../jalib/jassert.cpp:124
#6  0xf7e90893 in jalib_init (jalibFuncPtrs=..., 
    elfInterpreter=0xf7eacb5d "/lib64/ld-linux-x86-64.so.2", stderrFd=827, 
    jassertLogFd=828, dmtcp_fail_rc=99) at ../jalib/jalib.cpp:57
#7  0xf7e86a47 in initializeJalib () at jalibinterface.cpp:70
#8  0xf7e5165f in dmtcp::DmtcpWorker::DmtcpWorker (
    this=0xf7ece18d <dmtcp::DmtcpWorker::theInstance>) at dmtcpworker.cpp:313
#9  0xf7e52ce4 in __static_initialization_and_destruction_0 (__initialize_p=1, 
    __priority=65535) at dmtcpworker.cpp:306
#10 0xf7e52d26 in _GLOBAL__sub_I_dmtcpworker.cpp(void) () at dmtcpworker.cpp:632
#11 0xf7fec47e in _dl_init_internal () from /lib/ld-linux.so.2
#12 0xf7fde05f in _dl_start_user () from /lib/ld-linux.so.2
NOTE:
(gdb) frame 1
#1  0xf7e9e19e in initialize_libc_wrappers () at syscallsreal.c:265
265	    FOREACH_DMTCP_WRAPPER(GET_FUNC_ADDR);

Separately, in the second bug, on CentOS 6.6, with --enable-m32, it fails on restart.  If address space randomization is turned off, then this bug goes away.  With address space randomization turned on, and using the latest DMTCP (with the first bug fix from issue #56) and also with mtcp_check_vdso() being invoked, it still dumps core.

**Comment by gc00** [comment]
... and I see that DMTCP-2.0 does not have any bug here, for CentOS 7.  Later, I'll do a git bisect or other strategy to figure out the difference.  But I remember that we modified the way we handle wrapper functions somewhere between version 2.0 and the present.

**Comment by gc00** [comment]
And I've done a preliminary git-bisect.  I'll try to refine it further later.

The bug is in this range (for both CentOS 6.6 and CentOS 7):
git log 87ded92e0077baa7ec738702f49aeadfb66ab484..487eef9b5c0b1d7b2d676b469233c684cc9088fd
  12/25/13 to 2/21/14

And here are the summaries oof those commits:
# bad: [487eef9b5c0b1d7b2d676b469233c684cc9088fd] Remove JALIB stuff from mtcp/Makefile.in.
git bisect bad 487eef9b5c0b1d7b2d676b469233c684cc9088fd
# good: [87ded92e0077baa7ec738702f49aeadfb66ab484] IPC: Multi-arch support for sendFd/recvFd.
git bisect good 87ded92e0077baa7ec738702f49aeadfb66ab484

**Comment by gc00** [comment]
The bug is now in the range 1d6c4d1a59b1e137d6ca726453edf35a04acca0e..84601e31651e1819c54ce39b97b7b8a456cb3af6 (from 12/25/13 to 2/16/14).

**Comment by gc00** [comment]
The bug is now in the range ea3c10088da16ea0712c718ccd02268d36662463..603f895095ec84acfc2c08e6a587e9696da04418 (from 12/25/13 to 1/21/14).

**Comment by gc00** [comment]
I found the bug fix affecting standalone launch for m32.  I did a bisect by hand in the above range, and that gave me the clue for what was missing.  This bug fix (commit 9445ba7ef682876ad09483e31c4c6e5f10556289 ) affects only standalone m32, and not multi-arch.
This means that we still have a bug during restart when address randomization is turned on.  This bug occurs both for m32 standalone and for multi-arch.  The standalone case is issue #62 .

**Comment by gc00** [comment]
For the bug on restart, the bad commit is:  dec2c26c1eb13eb1c12edfdc9e8e811e4cc0e3c2  This was found by manually doing a git bisect using test/misc/multi-arch.sh at each step.  This agrees with the first bad commit found when running under 32-bit Ubuntu 9.10 (using a standard ./configure; make).  The commit message is (from 3/16/15):

    vDSO cleanup.   
    The newer vDSO/vvar sections are mremap()'d to the older vDSO/vvar addresses.

**Comment by gc00** [comment]
Commits 2cc8e7ed0d7c5e179125e8670348512699a757da and 2cc8e7ed0d7c5e179125e8670348512699a757da fix the two bugs listed here.
