### ISSUE TITLE
DMTCP with UCX

### ISSUE THREAD

**Issue by planetA** [dmtcp/dmtcp#694]
Hello,

is there support of [UCX](https://github.com/openucx/ucx) in DMTCP. Right now when I try to launch an MPI program compiled against a recent OpenMPI with UCX I get following error message:

> [42000] WARNING at socketconnection.cpp:231 in TcpConnection; REASON='JWARNING(false) failed'
>      type = 2
> Message: Datagram Sockets not supported. Hopefully, this is a short lived connection!
> [43000] WARNING at socketconnection.cpp:231 in TcpConnection; REASON='JWARNING(false) failed'
>      type = 2
> Message: Datagram Sockets not supported. Hopefully, this is a short lived connection!
> [43000] WARNING at signalwrappers.cpp:149 in sigaction; REASON='JWARNING(false) failed'
>      "Application trying to use DMTCP's signal for it's own use.\n" "  You should employ a different signal by setting the\n" "  environment variable DMTCP_SIGCKPT to the number\n" "  of the signal that DMTCP should use for checkpointing." = Application trying to use DMTCP's signal for it's own use.
>   You should employ a different signal by setting the
>   environment variable DMTCP_SIGCKPT to the number
>   of the signal that DMTCP should use for checkpointing.
>      stopSignal = 25
> [43000] WARNING at socketconnection.cpp:231 in TcpConnection; REASON='JWARNING(false) failed'
>      type = 2
> Message: Datagram Sockets not supported. Hopefully, this is a short lived connection!
> [42000] WARNING at socketconnection.cpp:231 in TcpConnection; REASON='JWARNING(false) failed'
>      type = 2
> Message: Datagram Sockets not supported. Hopefully, this is a short lived connection!
> [42000] WARNING at socketconnection.cpp:231 in TcpConnection; REASON='JWARNING(false) failed'
>      type = 2
> Message: Datagram Sockets not supported. Hopefully, this is a short lived connection!
> [42000] WARNING at socketconnection.cpp:231 in TcpConnection; REASON='JWARNING(false) failed'
>      type = 2
> Message: Datagram Sockets not supported. Hopefully, this is a short lived connection!
> 42000
> [42000] ERROR at sysvipcwrappers.cpp:92 in shmat; REASON='JASSERT(realShmid != -1) failed'
> Message: Not Implemented
> counter_mpi (42000): Terminating...
> [43000] WARNING at signalwrappers.cpp:149 in sigaction; REASON='JWARNING(false) failed'
>      "Application trying to use DMTCP's signal for it's own use.\n" "  You should employ a different signal by setting the\n" "  environment variable DMTCP_SIGCKPT to the number\n" "  of the signal that DMTCP should use for checkpointing." = Application trying to use DMTCP's signal for it's own use.
>   You should employ a different signal by setting the
>   environment variable DMTCP_SIGCKPT to the number
>   of the signal that DMTCP should use for checkpointing.
>      stopSignal = 25

Note that I set DMTCP_SIGCKPT to 25, but I used other numbers as well.

The actual error is:
> [42000] ERROR at sysvipcwrappers.cpp:92 in shmat; REASON='JASSERT(realShmid != -1) failed'
> Message: Not Implemented

The backtrace for this error is:

> #0  0x00007f30da41115e in shmat (shmid=0, shmaddr=0x0, shmflg=0) at svipc/sysvipcwrappers.cpp:91
> #1  0x00007f30c0cda5f4 in ucm_mmap_test (events=events@entry=54) at mmap/install.c:80
> #2  0x00007f30c0cda67d in ucm_mmap_test (events=54) at mmap/install.c:57
> #3  ucm_mmap_install (events=events@entry=54) at mmap/install.c:149
> #4  0x00007f30c0cd7ee1 in ucm_event_install (events=131072) at event/event.c:665
> #5  ucm_set_event_handler (events=events@entry=131072, priority=1000, 
>     cb=cb@entry=0x7f30c16b5c90 <ucs_rcache_unmapped_callback>, arg=arg@entry=0x55dcf13a0570) at event/event.c:708
> #6  0x00007f30c16b7b92 in ucs_rcache_t_init (stats_parent=0x0, name=<optimized out>, params=0x7ffd93626990, 
>     _init_count=<synthetic pointer>, _myclass=0x7f30c18caa60 <ucs_rcache_t_class>, self=0x55dcf13a0570)
>     at sys/rcache.c:675
> #7  ucs_rcache_create (arg0=arg0@entry=0x7ffd93626990, arg1=<optimized out>, arg2=arg2@entry=0x0, 
>     obj_p=obj_p@entry=0x55dcf1502ba0) at sys/rcache.c:715
> #8  0x00007f30c145cc06 in uct_ib_md_parse_reg_methods (md_config=0x55dcf14ffdf0, md=0x55dcf1502b90)
>     at ib/base/ib_md.c:1143
> #9  uct_ib_md_open (md_name=<optimized out>, uct_md_config=0x55dcf14ffdf0, md_p=0x7ffd93626aa8)
>     at ib/base/ib_md.c:1406
> #10 0x00007f30c1451999 in uct_md_open (md_name=md_name@entry=0x55dcf14365d0 "ib/mlx5_0", config=0x55dcf14ffdf0, 
>     md_p=md_p@entry=0x55dcf1501c30) at base/uct_md.c:124
> #11 0x00007f30c18dc20b in ucp_fill_tl_md (tl_md=0x55dcf1501c30, md_rsc=0x55dcf14365d0) at core/ucp_context.c:689
> #12 ucp_fill_resources (config=0x55dcf1441ba0, context=0x55dcf1501910) at core/ucp_context.c:871
> #13 ucp_init_version (api_major_version=<optimized out>, api_minor_version=<optimized out>, params=<optimized out>, 
>     config=0x55dcf1441ba0, context_p=0x7f30c1d3d318 <ompi_pml_ucx+184>) at core/ucp_context.c:1149
> #14 0x00007f30c1b38d61 in mca_pml_ucx_open ()
>    from <PATH>/lib/openmpi/mca_pml_ucx.so
> #15 0x00007f30d7f9d6b3 in mca_base_framework_components_open ()
>    from <PATH>/lib/libopen-pal.so.0
> #16 0x00007f30d9a51ce7 in mca_pml_base_open () from <PATH>/lib/libmpi.so.0
> #17 0x00007f30d7fa7d41 in mca_base_framework_open ()
>    from <PATH>/lib/libopen-pal.so.0
> #18 0x00007f30d99d07df in ompi_mpi_init () from <PATH>/lib/libmpi.so.0
> #19 0x00007f30d99fe65b in PMPI_Init () from <PATH>/lib/libmpi.so.0
> #20 0x000055dcf10eaa72 in main ()
>

**Comment by yxz900** [comment]
Hi,
Is it possible for you to share the patch for the shmat error?
Thanks!

**Comment by planetA** [comment]
@yxz900 Sorry for late response. It was quite silly from my side not to post patch immediately, because I cannot find it right now.
