### ISSUE TITLE
import dmtcp fails

### ISSUE THREAD

**Issue by haimivan** [dmtcp/dmtcp#724]
Hi,

I installed dmtcp in ubuntu 14.04 via the instructions in: https://github.com/dmtcp/dmtcp/blob/master/INSTALL.md

During the installation process, I also was asked to install dmtcp via the ubuntu package installation procedure (`sudo apt-get install dmtcp`), therefore it seems that I have now two different versions installed in parallel.

In the end, I face two difficulties presently:

1. `make check` fails with a:

```
make[1]: Leaving directory `/home/user/4me/Technologie/0010-install/0230-dmtcp-checkpoint-restart/dmtcp-2.5.2/test'
File "<string>", line 1
print "Python exits."
                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Python exits.")?
*** No python found in your path.
*** Please add  python to path or build Python 2.x for x >= 3.

```

But I have a working python installation on this computer:

```
$ which python
/home/user/anaconda3/bin/python

$python --version
Python 3.6.5 :: Anaconda custom (64-bit)

```

2. If I try to import `dmtcp` in Python, this fails:
Example:
I executed:

`dmtcp_checkpoint python`

```
dmtcp_checkpoint (DMTCP + MTCP) 1.2.5
Copyright (C) 2006-2011  Jason Ansel, Michael Rieker, Kapil Arya, and
                                                       Gene Cooperman
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see COPYING file for details.
(Use flag "-q" to hide this message.)

Python 3.6.5 |Anaconda custom (64-bit)| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```

And then I typed: `import dmtcp`.
This results in this error: 

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ModuleNotFoundError: No module named 'dmtcp'

**Comment by haimivan** [comment]
I managed to uninstall the old dmtcp version via `sudo apt-get remove dmtcp`. So, I have now the present version of dmtcp installed:
```
$dmtcp_coordinator --version
dmtcp_coordinator (DMTCP) 2.5.2
License LGPLv3+: GNU LGPL version 3 or later
    <http://gnu.org/licenses/lgpl.html>.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see COPYING file for details.

```

But still the `make check` fails. 
So my questions are:

**a) Is dmtcp meant to be installed on a Python3.x system, or is only a Python2.x installation foreseen?**

**b) should executing `dmtcp_checkpoint python` automatically make `dmtcp` available in a python shell, so that an `import dmtcp` works directly?**

**Comment by haimivan** [comment]
Hi, 

thanks for your reply. 

Indeed I meant http://iopscience.iop.org/article/10.1088/1749-4699/8/1/014005/meta .

In the moment, I am focussing to solve my usecase with some code I will program myself. Therefore, presently I have no further question.

Thanks again!
