### ISSUE TITLE
valgrind errors

### ISSUE THREAD

**Issue by gourryinverse** [dmtcp/dmtcp#912]
./test in this case is just a binary with "while(1);" sitting in a loop, just to see what falls out without any complex interactions

gourry@RagudoMezegis:~/git/dmtcp/bin$ valgrind --leak-check=full ./dmtcp_launch ./test

==15572== Memcheck, a memory error detector
==15572== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==15572== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==15572== Command: ./dmtcp_launch ./test
==15572==
==15572== Conditional jump or move depends on uninitialised value(s)
==15572==    at 0x11749E: dmtcp::CoordinatorAPI::getCoordHostAndPort(dmtcp::CoordinatorMode, std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> >*, int*) (coordinatorapi.cpp:202)
==15572==    by 0x11C266: dmtcp::CoordinatorAPI::startNewCoordinator(dmtcp::CoordinatorMode) (coordinatorapi.cpp:523)
==15572==    by 0x11CD56: dmtcp::CoordinatorAPI::createNewConnToCoord(dmtcp::CoordinatorMode) (coordinatorapi.cpp:600)
==15572==    by 0x11D4C9: dmtcp::CoordinatorAPI::connectToCoordOnStartup(dmtcp::CoordinatorMode, std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> >, DmtcpUniqueProcessId*, dmtcp::CoordinatorInfo*, in_addr*) (coordinatorapi.cpp:688)
==15572==    by 0x1125F5: main (dmtcp_launch.cpp:575)
==15572==
==15572== Syscall param write(buf) points to uninitialised byte(s)
==15572==    at 0x48782F7: write (write.c:26)
==15572==    by 0x133D27: dmtcp::Util::writeAll(int, void const*, unsigned long) (util_misc.cpp:161)
==15572==    by 0x11564A: dmtcp::CoordinatorAPI::sendMsgToCoordinatorRaw(int, dmtcp::DmtcpMessage, void const*, unsigned long) (coordinatorapi.cpp:406)
==15572==    by 0x11B065: dmtcp::CoordinatorAPI::sendRecvHandshake(int, dmtcp::DmtcpMessage, std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> >, dmtcp::UniquePid*) (coordinatorapi.cpp:642)
==15572==    by 0x11D5B4: dmtcp::CoordinatorAPI::connectToCoordOnStartup(dmtcp::CoordinatorMode, std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> >, DmtcpUniqueProcessId*, dmtcp::CoordinatorInfo*, in_addr*) (coordinatorapi.cpp:695)
==15572==    by 0x1125F5: main (dmtcp_launch.cpp:575)
==15572==  Address 0x1ffefff440 is on thread 1's stack
==15572==  in frame #3, created by dmtcp::CoordinatorAPI::sendRecvHandshake(int, dmtcp::DmtcpMessage, std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> >, dmtcp::UniquePid*) (coordinatorapi.cpp:626)
==15572==

gourry@RagudoMezegis:~/git/dmtcp/bin$ valgrind --leak-check=full ./dmtcp_launch valgrind ./test

==15594== Memcheck, a memory error detector
==15594== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==15594== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==15594== Command: ./dmtcp_launch valgrind ./test
==15594==
==15594== Conditional jump or move depends on uninitialised value(s)
==15594==    at 0x11749E: dmtcp::CoordinatorAPI::getCoordHostAndPort(dmtcp::CoordinatorMode, std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> >*, int*) (coordinatorapi.cpp:202)
==15594==    by 0x11C266: dmtcp::CoordinatorAPI::startNewCoordinator(dmtcp::CoordinatorMode) (coordinatorapi.cpp:523)
==15594==    by 0x11CD56: dmtcp::CoordinatorAPI::createNewConnToCoord(dmtcp::CoordinatorMode) (coordinatorapi.cpp:600)
==15594==    by 0x11D4C9: dmtcp::CoordinatorAPI::connectToCoordOnStartup(dmtcp::CoordinatorMode, std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> >, DmtcpUniqueProcessId*, dmtcp::CoordinatorInfo*, in_addr*) (coordinatorapi.cpp:688)
==15594==    by 0x1125F5: main (dmtcp_launch.cpp:575)
==15594==
==15594== Syscall param write(buf) points to uninitialised byte(s)
==15594==    at 0x48782F7: write (write.c:26)
==15594==    by 0x133D27: dmtcp::Util::writeAll(int, void const*, unsigned long) (util_misc.cpp:161)
==15594==    by 0x11564A: dmtcp::CoordinatorAPI::sendMsgToCoordinatorRaw(int, dmtcp::DmtcpMessage, void const*, unsigned long) (coordinatorapi.cpp:406)
==15594==    by 0x11B065: dmtcp::CoordinatorAPI::sendRecvHandshake(int, dmtcp::DmtcpMessage, std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> >, dmtcp::UniquePid*) (coordinatorapi.cpp:642)
==15594==    by 0x11D5B4: dmtcp::CoordinatorAPI::connectToCoordOnStartup(dmtcp::CoordinatorMode, std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> >, DmtcpUniqueProcessId*, dmtcp::CoordinatorInfo*, in_addr*) (coordinatorapi.cpp:695)
==15594==    by 0x1125F5: main (dmtcp_launch.cpp:575)
==15594==  Address 0x1ffefff430 is on thread 1's stack
==15594==  in frame #3, created by dmtcp::CoordinatorAPI::sendRecvHandshake(int, dmtcp::DmtcpMessage, std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> >, dmtcp::UniquePid*) (coordinatorapi.cpp:626)
==15594==
==15594== Memcheck, a memory error detector
==15594== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==15594== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==15594== Command: ./test
==15594==
==15594== Syscall param write(buf) points to uninitialised byte(s)
==15594==    at 0x4ADB1E7: write (write.c:26)
==15594==    by 0x4958567: dmtcp::Util::writeAll(int, void const*, unsigned long) (util_misc.cpp:161)
==15594==    by 0x4938A4A: dmtcp::CoordinatorAPI::sendMsgToCoordinatorRaw(int, dmtcp::DmtcpMessage, void const*, unsigned long) (coordinatorapi.cpp:406)
==15594==    by 0x49392A1: dmtcp::CoordinatorAPI::sendMsgToCoordinator(dmtcp::DmtcpMessage const&, std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> > const&) (coordinatorapi.cpp:468)
==15594==    by 0x4939DC8: dmtcp::CoordinatorAPI::init() (coordinatorapi.cpp:249)
==15594==    by 0x492782E: dmtcp::PluginManager::eventHook(eDmtcpEvent, _DmtcpEventData_t*) (pluginmanager.cpp:98)
==15594==    by 0x491A4F7: dmtcp_initialize_entry_point (dmtcpworker.cpp:292)
==15594==    by 0x4011C49: call_init.part.0 (dl-init.c:72)
==15594==    by 0x4011D50: call_init (dl-init.c:30)
==15594==    by 0x4011D50: _dl_init (dl-init.c:119)
==15594==    by 0x4001139: ??? (in /usr/lib/x86_64-linux-gnu/ld-2.31.so)
==15594==  Address 0x1ffefff480 is on thread 1's stack
==15594==  in frame #3, created by dmtcp::CoordinatorAPI::sendMsgToCoordinator(dmtcp::DmtcpMessage const&, std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> > const&) (coordinatorapi.cpp:467)
==15594==
==15594== Thread 2:
==15594== Conditional jump or move depends on uninitialised value(s)
==15594==    at 0x4DCAE76: pthread_sigmask (pthread_sigmask.c:34)
==15594==    by 0x4932D6E: pthread_start(void*) (threadwrappers.cpp:162)
==15594==    by 0x4DC2608: start_thread (pthread_create.c:477)
==15594==    by 0x4932CE6: clone_start(void*) (threadwrappers.cpp:66)
==15594==    by 0x4AEC292: clone (clone.S:95)
==15594==
==15594== Syscall param rt_sigprocmask(set) points to uninitialised byte(s)
==15594==    at 0x4DCAE8B: pthread_sigmask (pthread_sigmask.c:50)
==15594==    by 0x4932D6E: pthread_start(void*) (threadwrappers.cpp:162)
==15594==    by 0x4DC2608: start_thread (pthread_create.c:477)
==15594==    by 0x4932CE6: clone_start(void*) (threadwrappers.cpp:66)
==15594==    by 0x4AEC292: clone (clone.S:95)
==15594==  Address 0x7d89c40 is on thread 2's stack
==15594==  in frame #1, created by pthread_start(void*) (threadwrappers.cpp:145)
==15594==

**Comment by gourryinverse** [comment]
also dmtcp crashes when checkpointing valgrind 

running ./dmtcp_command -c in a separate window while this is running.
In this case, test is a problem with
while (1)
{
    sleep(2);
    printf(".");
}

gourry@RagudoMezegis:~/git/dmtcp/bin$ ./dmtcp_launch valgrind ./test

==15753== Memcheck, a memory error detector
==15753== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==15753== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==15753== Command: ./test
==15753==
==15753== Syscall param write(buf) points to uninitialised byte(s)
==15753==    at 0x4ADB1E7: write (write.c:26)
==15753==    by 0x4958567: dmtcp::Util::writeAll(int, void const*, unsigned long) (util_misc.cpp:161)
==15753==    by 0x4938A4A: dmtcp::CoordinatorAPI::sendMsgToCoordinatorRaw(int, dmtcp::DmtcpMessage, void const*, unsigned long) (coordinatorapi.cpp:406)
==15753==    by 0x49392A1: dmtcp::CoordinatorAPI::sendMsgToCoordinator(dmtcp::DmtcpMessage const&, std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> > const&) (coordinatorapi.cpp:468)
==15753==    by 0x4939DC8: dmtcp::CoordinatorAPI::init() (coordinatorapi.cpp:249)
==15753==    by 0x492782E: dmtcp::PluginManager::eventHook(eDmtcpEvent, _DmtcpEventData_t*) (pluginmanager.cpp:98)
==15753==    by 0x491A4F7: dmtcp_initialize_entry_point (dmtcpworker.cpp:292)
==15753==    by 0x4011C49: call_init.part.0 (dl-init.c:72)
==15753==    by 0x4011D50: call_init (dl-init.c:30)
==15753==    by 0x4011D50: _dl_init (dl-init.c:119)
==15753==    by 0x4001139: ??? (in /usr/lib/x86_64-linux-gnu/ld-2.31.so)
==15753==  Address 0x1ffefff5c0 is on thread 1's stack
==15753==  in frame #3, created by dmtcp::CoordinatorAPI::sendMsgToCoordinator(dmtcp::DmtcpMessage const&, std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> > const&) (coordinatorapi.cpp:467)
==15753==
==15753== Thread 2:
==15753== Conditional jump or move depends on uninitialised value(s)
==15753==    at 0x4DCAE76: pthread_sigmask (pthread_sigmask.c:34)
==15753==    by 0x4932D6E: pthread_start(void*) (threadwrappers.cpp:162)
==15753==    by 0x4DC2608: start_thread (pthread_create.c:477)
==15753==    by 0x4932CE6: clone_start(void*) (threadwrappers.cpp:66)
==15753==    by 0x4AEC292: clone (clone.S:95)
==15753==
==15753== Syscall param rt_sigprocmask(set) points to uninitialised byte(s)
==15753==    at 0x4DCAE8B: pthread_sigmask (pthread_sigmask.c:50)
==15753==    by 0x4932D6E: pthread_start(void*) (threadwrappers.cpp:162)
==15753==    by 0x4DC2608: start_thread (pthread_create.c:477)
==15753==    by 0x4932CE6: clone_start(void*) (threadwrappers.cpp:66)
==15753==    by 0x4AEC292: clone (clone.S:95)
==15753==  Address 0x7d89c40 is on thread 2's stack
==15753==  in frame #1, created by pthread_start(void*) (threadwrappers.cpp:145)
==15753==
==15753== Syscall param write(buf) points to uninitialised byte(s)
==15753==    at 0x4ADB21F: __libc_write (write.c:26)
==15753==    by 0x4ADB21F: write (write.c:24)
==15753==    by 0x4958567: dmtcp::Util::writeAll(int, void const*, unsigned long) (util_misc.cpp:161)
==15753==    by 0x4938AB4: dmtcp::CoordinatorAPI::sendMsgToCoordinatorRaw(int, dmtcp::DmtcpMessage, void const*, unsigned long) (coordinatorapi.cpp:406)
==15753==    by 0x493A08B: dmtcp::CoordinatorAPI::waitForBarrier(std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> > const&, unsigned int*) (coordinatorapi.cpp:490)
==15753==    by 0x492046E: dmtcp::DmtcpWorker::waitForCheckpointRequest() (dmtcpworker.cpp:417)
==15753==    by 0x4930C9F: checkpointhread(void*) (threadlist.cpp:420)
==15753==    by 0x4932E9C: pthread_start(void*) (threadwrappers.cpp:165)
==15753==    by 0x4DC2608: start_thread (pthread_create.c:477)
==15753==    by 0x4932CE6: clone_start(void*) (threadwrappers.cpp:66)
==15753==    by 0x4AEC292: clone (clone.S:95)
==15753==  Address 0x7d892e0 is on thread 2's stack
==15753==  in frame #3, created by dmtcp::CoordinatorAPI::waitForBarrier(std::__cxx11::basic_string<char, std::char_traits<char>, dmtcp::DmtcpAlloc<char> > const&, unsigned int*) (coordinatorapi.cpp:479)
==15753==
==15753== Syscall param msync(start) points to unaddressable byte(s)
==15753==    at 0x4AE5B7F: msync (msync.c:25)
==15753==    by 0x488F371: dmtcp::FileConnList::prepareShmList() (fileconnlist.cpp:401)
==15753==    by 0x488FC4C: dmtcp::FileConnList::preLockSaveOptions() (fileconnlist.cpp:258)
==15753==    by 0x488F025: saveOptions (fileconnlist.h:49)
==15753==    by 0x488F025: dmtcp_FileConnList_EventHook(eDmtcpEvent, _DmtcpEventData_t*) (fileconnlist.cpp:142)
==15753==    by 0x4927979: dmtcp::PluginManager::eventHook(eDmtcpEvent, _DmtcpEventData_t*) (pluginmanager.cpp:136)
==15753==    by 0x492069C: dmtcp::DmtcpWorker::preCheckpoint() (dmtcpworker.cpp:460)
==15753==    by 0x4930CB3: checkpointhread(void*) (threadlist.cpp:427)
==15753==    by 0x4932E9C: pthread_start(void*) (threadwrappers.cpp:165)
==15753==    by 0x4DC2608: start_thread (pthread_create.c:477)
==15753==    by 0x4932CE6: clone_start(void*) (threadwrappers.cpp:66)
==15753==    by 0x4AEC292: clone (clone.S:95)
==15753==  Address 0x1002cac000 is not stack'd, malloc'd or (recently) free'd
==15753==
[40000] ERROR at fileconnlist.cpp:427 in prepareShmList; REASON='JASSERT(mmap(area.addr, area.size, PROT_NONE, MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED, -1, 0) != MAP_FAILED) failed'
     (strerror((*__errno_location ()))) = Invalid argument
test (40000): Terminating...
==15753==
==15753== HEAP SUMMARY:
==15753==     in use at exit: 2,432 bytes in 3 blocks
==15753==   total heap usage: 4 allocs, 1 frees, 75,136 bytes allocated
==15753==
==15753== LEAK SUMMARY:
==15753==    definitely lost: 0 bytes in 0 blocks
==15753==    indirectly lost: 0 bytes in 0 blocks
==15753==      possibly lost: 352 bytes in 1 blocks
==15753==    still reachable: 2,080 bytes in 2 blocks
==15753==         suppressed: 0 bytes in 0 blocks
==15753== Rerun with --leak-check=full to see details of leaked memory
==15753==
==15753== Use --track-origins=yes to see where uninitialised values come from
==15753== For lists of detected and suppressed errors, rerun with: -s
==15753== ERROR SUMMARY: 6 errors from 5 contexts (suppressed: 0 from 0)

**Comment by gc00** [comment]
Hi,
    Yes, you're correct.  DMTCP does not support Valgrind.  It's because both are doing things at a low level, and they interfere with each other.
    Some other tools that you could look at instead of Valgrind are:
 *  AddressSanitizer ( -sanitize=address ) available from gcc and clang, although the clang version has more options
 * ElectricFence:  https://github.com/kallisti5/ElectricFence    (an old tool with various limitations, but it can still be useful in some situations)

Best,
- Gene

________________________________________

**Comment by zouyonghao** [comment]
> Hi, Yes, you're correct. DMTCP does not support Valgrind. It's because both are doing things at a low level, and they interfere with each other. Some other tools that you could look at instead of Valgrind are: * AddressSanitizer ( -sanitize=address ) available from gcc and clang, although the clang version has more options * ElectricFence: https://github.com/kallisti5/ElectricFence (an old tool with various limitations, but it can still be useful in some situations) Best, - Gene

Hi, Gene

Actually I tested some programs compiled with ASan, and it also crashed.
The following trace may help:

```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff7ebfcaf in dlsym_default_internal_library_handler (handle=<optimized out>, symbol=0x7ffff7efa9f0 "dlopen", version=0x0, 
    tags_p=0x7fffffffd830, default_symbol_index_p=0x7fffffffd82c) at dmtcp_dlsym.cpp:338
#2  0x00007ffff7ec05bf in dlsym_default_internal_flag_handler (handle=0xffffffffffffffff, libname=0x0, symbol=0x7ffff7efa9f0 "dlopen", 
    version=0x0, addr=<optimized out>, tags_p=0x7fffffffd830, default_symbol_index_p=0x7fffffffd82c) at dmtcp_dlsym.cpp:435
#3  0x00007ffff7ec06a0 in dmtcp_dlsym (handle=handle@entry=0xffffffffffffffff, symbol=symbol@entry=0x7ffff7efa9f0 "dlopen")
    at dmtcp_dlsym.cpp:502
#4  0x00007ffff7ee8e77 in initialize_libc_wrappers () at syscallsreal.c:284
#5  dmtcp_prepare_wrappers () at syscallsreal.c:284
#6  0x00007ffff7e9f778 in dmtcp_initialize () at dmtcpworker.cpp:283
#7  0x00007ffff7f4237f in dlsym (handle=0xffffffffffffffff, symbol=0x4cef1c "mmap") at svipc/sysvipcwrappers.cpp:159
#8  0x00000000004a3663 in __interception::InterceptFunction(char const*, unsigned long*, unsigned long, unsigned long) ()
#9  0x0000000000484b3e in InitializeCommonInterceptors() ()
#10 0x000000000048437a in __asan::InitializeAsanInterceptors() ()
#11 0x000000000049eeae in __asan::AsanInitInternal() ()
#12 0x00007ffff7fe0ce6 in ?? () from /lib64/ld-linux-x86-64.so.2
#13 0x00007ffff7fd013a in ?? () from /lib64/ld-linux-x86-64.so.2
#14 0x0000000000000003 in ?? ()
#15 0x00007fffffffdfac in ?? ()
#16 0x00007fffffffdfca in ?? ()
#17 0x00007fffffffdfcc in ?? ()
#18 0x0000000000000000 in ?? ()
```

**Comment by gourryinverse** [comment]
@gc00 i would imagine you can just add "-fsanitize=address" to any of your sample programs that you checkpoint.  There shouldn't be any special dependencies or setup, just natively supported by gcc

**Comment by gourryinverse** [comment]
would actually be interested to see what happens if you compile DMTCP under address sanitization lol
