### ISSUE TITLE
Warning: Couldn't find offsets of tid/pid in thread_area

### ISSUE THREAD

**Issue by JainTwinkle** [dmtcp/dmtcp#994]
With `gcc-9`, dmtcp_launch throws the following warning:
```
$ ../bin/dmtcp_launch ./dmtcp1
[40000] WARNING at tls.cpp:256 in TLSInfo_GetTidOffset; REASON='JWARNING(false) failed'
     tid_pid.tid = 1442
Message: Couldn't find offsets of tid/pid in thread_area.
  Now relying on the value determined using the
  glibc version with which DMTCP was compiled.
[40000] WARNING at tls.cpp:256 in TLSInfo_GetTidOffset; REASON='JWARNING(false) failed'
     tid_pid.tid = 1442
Message: Couldn't find offsets of tid/pid in thread_area.
  Now relying on the value determined using the
  glibc version with which DMTCP was compiled.
[40000] WARNING at tls.cpp:256 in TLSInfo_GetTidOffset; REASON='JWARNING(false) failed'
     tid_pid.tid = 1442
Message: Couldn't find offsets of tid/pid in thread_area.
  Now relying on the value determined using the
  glibc version with which DMTCP was compiled.
[40000] WARNING at tls.cpp:256 in TLSInfo_GetTidOffset; REASON='JWARNING(false) failed'
     tid_pid.tid = 1448
Message: Couldn't find offsets of tid/pid in thread_area.
  Now relying on the value determined using the
  glibc version with which DMTCP was compiled.
```

System information:
```
gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
ldd (GNU libc) 2.17
OS: CentOs 7.9.2009
```

The comment at [tls.cpp#L249](https://github.com/dmtcp/dmtcp/blob/138dbe086d147b0255a4b3e03a53f67b5dd4d0ba/src/tls.cpp#L249) mentions about glibc-2.25 but I'm using glibc 2.17.

**Comment by JainTwinkle** [comment]
Information from a GDB session:
```
(gdb) bt
#0  TLSInfo_GetTidOffset () at tls.cpp:248
#1  0x00007ffff7ecd149 in TLSInfo_GetPidOffset () at tls.cpp:300
#2  0x00007ffff7ecd234 in TLSInfo_VerifyPidTid (pid=8518, tid=8518) at tls.cpp:604
#3  0x00007ffff7ed2e68 in dmtcp::ThreadList::init () at threadlist.cpp:179
#4  0x00007ffff7ebe956 in dmtcp_initialize_entry_point () at dmtcpworker.cpp:293
#5  0x00007ffff7dea9c3 in call_init (env=0x7fffffffdd08, argv=0x7fffffffdcf8, argc=1, l=<optimized out>) at dl-init.c:82
#6  _dl_init (main_map=0x7ffff7ffe150, argc=1, argv=0x7fffffffdcf8, env=0x7fffffffdd08) at dl-init.c:131
#7  0x00007ffff7ddc17a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#8  0x0000000000000001 in ?? ()
#9  0x00007fffffffdfd9 in ?? ()
#10 0x0000000000000000 in ?? ()
(gdb) l
243          * 'struct pthread' is zeroed out before adding tid and pid.
244          * pthread_desc below is defined as 'struct pthread' in glibc:nptl/descr.h
245          */
246         tmp = memsubarray((char *)pthread_desc, (char *)&tid_pid, sizeof(tid_pid));
247
248         if (tmp == NULL && glibcMajorVersion() == 2 && glibcMinorVersion() >= 24) {
249           // starting with glibc-2.25 (including 2.24.90 on Fedora), the pid field
250           // is deprecated and set to zero.
251           tid_pid.pid = 0;
252           tmp = memsubarray((char*)pthread_desc, (char *)&tid_pid, sizeof(tid_pid));
(gdb) l
253         }
254
255         if (tmp == NULL) {
256           JWARNING(false) (tid_pid.tid)
257             .Text("Couldn't find offsets of tid/pid in thread_area.\n"
258                   "  Now relying on the value determined using the\n"
259                   "  glibc version with which DMTCP was compiled.");
260           return STATIC_TLS_TID_OFFSET();
261
262           // mtcp_abort();
(gdb) p tmp
$3 = 0x0
(gdb) p glibcMinorVersion()
$6 = 17
(gdb) p glibcMajorVersion()
$7 = 2
```

**Comment by karya0** [comment]
Thanks for the diagnosis, @JainTwinkle. I just looked and threadlist certainly has a couple of discrepancies around pid handling. I'll create a PR to clean it up.
